---
title: "Long Beach Animal Shelter"
description: |
  Analysis of Long Beach Animal Shelter data from Tidy Tuesday
author: Ava Santos-Volpe
date: September 24, 2025
format: 
  html:
    code-fold: true
    code-summary: "Show the code"
execute:
   warning: false
   message: false
---

# Data

The dataset comes from the [City of Long Beach Animal Care Services](https://www.longbeach.gov/acs/) via the {animalshelter} R package. This dataset comprises of the intake and outcome record from Long Beach Animal Shelter.

Thank you to Lydia Gibson for curating this week's dataset.

[Tidy Tuesday Link](https://github.com/rfordatascience/tidytuesday/blob/main/data/2025/2025-03-04/readme.md)

Reference: City of Long Beach Animal Care Services (2025)

```{r}
#| label: animal_types

library(dplyr)
library(tidyverse)

longbeach <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-03-04/longbeach.csv')

ggplot(
  longbeach, aes(x = animal_type, fill = animal_type)
) +
  geom_bar(position = "stack") +
  labs(
    x = "Animal Type",
    y = "Count",
    title = "Types of Animals at Long Beach Animal Shelter", 
    fill = "Animal Type"
  )
```

```{r}
#| label: animal_names

library(dplyr)
library(tidyverse)
library(shiny)
library(wordcloud2)
library(DT)

# prep names
name_counts <- longbeach |>
  mutate(animal_name = str_remove(animal_name, "^\\*")) |>
  filter(!is.na(animal_name)) |>
  filter(animal_name != "*") |>
  group_by(animal_name) |>
  summarize(n = n()) |>
  arrange(desc(n))

# UI
ui <- fluidPage(
  titlePanel("Animal Names"),

  tags$script(HTML(
    "$(document).on('click', '#canvas', function() {
      word = $('#wcLabel').text();
      Shiny.onInputChange('clicked_word', word);
    });"
  )),
  wordcloud2Output("wordcloud"),
  DTOutput("filtered_tbl")
)

server <- function(input, output) {
  output$wordcloud <- renderWordcloud2({
    wordcloud2(name_counts)
  })
  
filtered_name <- reactive({
    clicked_word <- input$clicked_word
  
    longbeach |>
    mutate(animal_name = str_remove(animal_name, "^\\*"))
  })
    
  output$filtered_tbl <- renderDT({
    filtered_name()
  })
}

shinyApp(ui, server)
```

