---
title: "Data Ethics"
editor: source
description: |
  Havasupai Tribe vs. Arizona Board of Regents
author: Ava Santos-Volpe
date: November 8, 2025
format: 
  html:
    code-fold: true
    code-summary: "Show the code"
execute:
  warning: false
  message: false
---

The ethical dilemma I chose to learn about for this project is the Havasupai Tribe vs. the Arizona Board of Regents. I chose an academic article and an interview with Carletta Tilousi (a member of the Havasupai Tribe and the blood case liaison for the Havasupai Tribe and Arizona State University). 

This case is about the issue of informed consent, ethics of "anonymous" samples, and the right to withdraw consent (Van Assche et. al, 2013). The Havasupai tribe originally agreed to giving blood samples to a trusted researcher at Arizona State University (ASU) to study the high rates of type 2 diabetes within their tribe (Van Assche et. al, 2013). This researcher then brought on a genetic specialist who, without their explicit consent, used the blood samples for other purposes (Van Assche et. al, 2013). These purposes include studies investigating mental illness, inbreeding, migratory patterns, and the distribution of the samples to other institutions (Van Assche et. al, 2013; Headlee, 2014). The geneticist, was able to get "consent" for these projects by creating a very vague consent form for participants to agree to (Van Assche et. al, 2013). However, the participants were convinced to join the study to determine if they would get diabetes in the future (Headlee, 2014). 

Not only did Carletta Tilousi not get her answer to the supposed question, but the studies also had many undesirable effects on the Havasupai community (Van Assche et. al, 2013; Headlee, 2014). In her interview, Tilousi states that the blood was a part of their bodies that was taken from them without true consent to what they would be used for (NPR, 2014). Many professors and students within the Arizona school system were profiting off of these blood samples, when the participants in the study had no idea that this was what they were being used for (Headlee, 2014). Not only that, but these studies also led to tangible harms for the Havasupai tribe. These harms include stigmatization of indivduals within the tribe, mistrust of medical care, and results which contradict their own beliefs (Van Assche et. al, 2013). 

This is both a data science issue and an ethical dilemma. The data science aspect of this issue involves the collection/use of the blood samples (data). The ethical dilemma involves the issue of informed consent and use of samples without truly informing the participants. 

I will be responding to the following four questions about the use of this data:

1. What was the consent structure for recruiting participants? Were the participants aware of the ways their data would be used for research? Was informed consent possible? Can you provide informed consent for applications that are yet foreseen?

The consent structure for recruiting participants involved asking participants if they were interested in knowing their potential risk for getting diabetes in the future (Headlee, 2014). Not only was the answer to this question never given to participants, but their data was also used to study topics that they were unaware of (Van Assche et. al, 2013; Headlee, 2014). There was definitely a way to get informed consent in this study, but it was not obtained for any studies outside of the type 2 diabetes one. Additionally, if a researcher decides to move the study in a different direction, they should be responsible for obtaining consent from participants again. 

2. Were the data made publicly available? Why? How? On what platform?

The data collected from participants of this study was made available through studies on schizophrenia, inbreeding, and population migration (Van Assche et. al, 2013). A report on this case found that at least 23 scholarly articles/dissertations were published using data from the Havasupai blood samples. The data itself, however, was not made public. One of the researchers sent the blood samples to various universities outside of ASU (Van Assche et. al, 2013). However, the consent form had ensured participants that their data would not leave ASU (Van Assche et. al, 2013). 

3. Did this study use data to improve life for users, customers, organizations, and communities?

This study did not improve life for the Havasupai community. In fact, it caused many negative effects such as stigmatization within the tribe, medical distrust, and the study results contradicted their beliefs about themselves (Van Assche et. al, 2013). This data did, however, allow many students and professors to profit by publishing papers and dissertations (Headlee, 2014).

4. Is the data being used in unintended ways to the original study?

Yes, the original intention behind the study, and the way the study was marketed to participants, was to determine the reasoning behind high rates of type 2 diabetes within the tribe (Van Assche et. al, 2013; Headlee, 2014). Instead, this data was used for studies on schizophrenia, inbreeding, and population migration (Van Assche et. al, 2013). This was not something that the tribe consented to (Van Assche et. al, 2013; Headlee, 2014). 


Given the information stated above, this case is extremely important. It shows how people within an academic setting benefited off of people who were not properly informed. These ethical violations were in the interest of profit, as over 20 publications and dissertations were published using this data (Van Assche et. al, 2013). This case is important, not only for the Havasupai tribe, but also for anyone participating in studies in the US. This case changed the laws for human subject research and requires researchers to get true informed consent, especially for participants whose first language is not English (Headlee, 2014). 

References:

Van Assche, K., Gutwirth, S., and Sterckx, S. (2013), [Protecting Dignitary Interests of Biobank Research Participants: Lessons from Havasupai Tribe v Arizona Board of Regents, Law, Innovation and Technology](https://www.researchgate.net/publication/260121496_Protecting_Dignitary_Interests_of_Biobank_Research_Participants_Lessons_from_Havasupai_Tribe_v_Arizona_Board_of_RegentsI), 5, 54–84.

Headlee, C. (2014), ['Blood Victory' In Medical Research Dispute](https://www.npr.org/2014/04/25/306832661/blood-victory-in-medical-research-dispute)

